spring:
  application:
    name: CloudConfigServer-1
    
 
 
    
  cloud:
      config:
       server:
        git:
           uri: https://github.com/debasishgorai/SPRING-CLOUD-CONFIG
           
server:  
  port: 9093